// The "Insert base C4 model" buttons (shown when a board has no containers
// yet) drop one of these onto the canvas — the three canonical "Big Bank
// plc" example diagrams from the official C4 model documentation
// (https://c4model.com/diagrams), reused across the C4 abstraction levels so
// a new user sees a real, recognizable C4 diagram rather than an empty
// board:
//   Level 1 — System Context  (c4model.com/diagrams/system-context)
//   Level 2 — Container       (c4model.com/diagrams/container)
//   Level 3 — Component       (c4model.com/diagrams/component)
import type { LikeC4View } from './likec4-types'

// Level 1 — System Context: the customer, the Internet Banking System, and
// the two external systems it talks to.
export const LEVEL1_TEMPLATE: LikeC4View = {
  id: 'base-c4-level1-system-context',
  title: 'System Context diagram (example)',
  description: null,
  bounds: { x: 0, y: 0, width: 1120, height: 760 },
  nodes: [
    {
      id: 'customer',
      parent: null,
      title: 'Personal Banking Customer',
      description: 'A customer of the bank, with personal bank accounts.',
      kind: 'person',
      shape: 'person',
      level: 0,
      children: [],
      x: 40,
      y: 40,
      width: 200,
      height: 172,
    },
    {
      id: 'ibs',
      parent: null,
      title: 'Internet Banking System',
      description:
        'Allows customers to view information about their bank accounts and make payments.',
      kind: 'softwareSystem',
      level: 0,
      children: [],
      x: 340,
      y: 300,
      width: 320,
      height: 182,
    },
    {
      id: 'mbs',
      parent: null,
      title: 'Mainframe Banking System',
      description:
        'Stores all of the core banking information about customers, accounts, transactions, etc.',
      kind: 'externalSystem',
      level: 0,
      children: [],
      x: 760,
      y: 540,
      width: 320,
      height: 182,
    },
    {
      id: 'email',
      parent: null,
      title: 'E-mail System',
      description: 'The internal Microsoft Exchange e-mail system.',
      kind: 'externalSystem',
      level: 0,
      children: [],
      x: 760,
      y: 40,
      width: 320,
      height: 182,
    },
  ],
  edges: [
    {
      id: 'customer-ibs',
      parent: null,
      source: 'customer',
      target: 'ibs',
      label: 'Views account balances, and makes payments using',
      points: [],
    },
    {
      id: 'ibs-mbs',
      parent: null,
      source: 'ibs',
      target: 'mbs',
      label: 'Gets account information from, and makes payments using',
      points: [],
    },
    {
      id: 'ibs-email',
      parent: null,
      source: 'ibs',
      target: 'email',
      label: 'Sends e-mail using',
      points: [],
    },
    {
      id: 'email-customer',
      parent: null,
      source: 'email',
      target: 'customer',
      label: 'Sends e-mails to',
      points: [],
    },
  ],
}

// Level 2 — Container: the Internet Banking System decomposed into its
// containers (SPA, mobile app, web app, API, database).
export const LEVEL2_TEMPLATE: LikeC4View = {
  id: 'base-c4-level2-container',
  title: 'Container diagram (example)',
  description: null,
  bounds: { x: 0, y: 0, width: 1560, height: 760 },
  nodes: [
    {
      id: 'customer',
      parent: null,
      title: 'Personal Banking Customer',
      description: 'A customer of the bank, with personal bank accounts.',
      kind: 'person',
      shape: 'person',
      level: 0,
      children: [],
      x: 40,
      y: -160,
      width: 200,
      height: 172,
    },
    {
      id: 'ibs',
      parent: null,
      title: 'Internet Banking System',
      kind: 'softwareSystem',
      level: 0,
      children: ['spa', 'mobileapp', 'webapp', 'api', 'database'],
      x: 360,
      y: 40,
      width: 760,
      height: 740,
    },
    {
      id: 'spa',
      parent: 'ibs',
      title: 'Single-Page Application',
      description:
        'Provides all of the Internet banking functionality to customers via their web browser.',
      technology: 'JavaScript, Angular',
      kind: 'container',
      shape: 'browser',
      level: 1,
      children: [],
      x: 400,
      y: 80,
      width: 300,
      height: 175,
    },
    {
      id: 'mobileapp',
      parent: 'ibs',
      title: 'Mobile App',
      description:
        'Provides a limited subset of the Internet banking functionality to customers via their mobile device.',
      technology: 'Xamarin',
      kind: 'container',
      shape: 'mobile',
      level: 1,
      children: [],
      x: 780,
      y: 80,
      width: 300,
      height: 175,
    },
    {
      id: 'webapp',
      parent: 'ibs',
      title: 'Web Application',
      description:
        "Delivers the static content and the Internet banking single-page application.",
      technology: 'Java, Spring MVC',
      kind: 'container',
      shape: 'browser',
      level: 1,
      children: [],
      x: 400,
      y: 355,
      width: 300,
      height: 175,
    },
    {
      id: 'api',
      parent: 'ibs',
      title: 'API Application',
      description:
        'Provides Internet banking functionality via a JSON/HTTPS API.',
      technology: 'Java, Spring MVC',
      kind: 'backend',
      level: 1,
      children: [],
      x: 780,
      y: 355,
      width: 300,
      height: 175,
    },
    {
      id: 'database',
      parent: 'ibs',
      title: 'Database',
      description:
        'Stores user registration information, hashed authentication credentials, access logs, etc.',
      technology: 'Oracle Database',
      kind: 'database',
      shape: 'database',
      level: 1,
      children: [],
      x: 590,
      y: 570,
      width: 300,
      height: 166,
    },
    {
      id: 'mbs',
      parent: null,
      title: 'Mainframe Banking System',
      description:
        'Stores all of the core banking information about customers, accounts, transactions, etc.',
      kind: 'externalSystem',
      level: 0,
      children: [],
      x: 1200,
      y: 480,
      width: 320,
      height: 182,
    },
    {
      id: 'email',
      parent: null,
      title: 'E-mail System',
      description: 'The internal Microsoft Exchange e-mail system.',
      kind: 'externalSystem',
      level: 0,
      children: [],
      x: 1200,
      y: -160,
      width: 320,
      height: 182,
    },
  ],
  edges: [
    {
      id: 'customer-webapp',
      parent: null,
      source: 'customer',
      target: 'webapp',
      label: 'Visits bigbank.com using [HTTPS]',
      points: [],
    },
    {
      id: 'customer-mobileapp',
      parent: null,
      source: 'customer',
      target: 'mobileapp',
      label: 'Views account balances, and makes payments using',
      points: [],
    },
    {
      id: 'webapp-spa',
      parent: null,
      source: 'webapp',
      target: 'spa',
      label: "Delivers to the customer's web browser",
      points: [],
    },
    {
      id: 'spa-api',
      parent: null,
      source: 'spa',
      target: 'api',
      label: 'Makes API calls to [JSON/HTTPS]',
      points: [],
    },
    {
      id: 'mobileapp-api',
      parent: null,
      source: 'mobileapp',
      target: 'api',
      label: 'Makes API calls to [JSON/HTTPS]',
      points: [],
    },
    {
      id: 'api-database',
      parent: null,
      source: 'api',
      target: 'database',
      label: 'Reads from and writes to [SQL/TCP]',
      points: [],
    },
    {
      id: 'api-mbs',
      parent: null,
      source: 'api',
      target: 'mbs',
      label: 'Makes API calls to [XML/HTTPS]',
      points: [],
    },
    {
      id: 'api-email',
      parent: null,
      source: 'api',
      target: 'email',
      label: 'Sends e-mail using',
      points: [],
    },
    {
      id: 'email-customer',
      parent: null,
      source: 'email',
      target: 'customer',
      label: 'Sends e-mails to',
      points: [],
    },
  ],
}

// Level 3 — Component: the API Application decomposed into its components.
export const LEVEL3_TEMPLATE: LikeC4View = {
  id: 'base-c4-level3-component',
  title: 'Component diagram (example)',
  description: null,
  bounds: { x: 0, y: 0, width: 1880, height: 560 },
  nodes: [
    {
      id: 'spa',
      parent: null,
      title: 'Single-Page Application',
      technology: 'JavaScript, Angular',
      kind: 'container',
      shape: 'browser',
      level: 0,
      children: [],
      x: 40,
      y: 80,
      width: 300,
      height: 175,
    },
    {
      id: 'mobileapp',
      parent: null,
      title: 'Mobile App',
      technology: 'Xamarin',
      kind: 'container',
      shape: 'mobile',
      level: 0,
      children: [],
      x: 40,
      y: 295,
      width: 300,
      height: 175,
    },
    {
      id: 'api',
      parent: null,
      title: 'API Application',
      kind: 'container',
      level: 0,
      children: [
        'signin',
        'accountssummary',
        'resetpw',
        'security',
        'mbsfacade',
        'emailcomponent',
      ],
      x: 400,
      y: 40,
      width: 1060,
      height: 470,
    },
    {
      id: 'signin',
      parent: 'api',
      title: 'Sign In Controller',
      description: 'Allows users to sign in to the Internet banking system.',
      technology: 'Spring MVC Rest Controller',
      kind: 'component',
      level: 1,
      children: [],
      x: 440,
      y: 80,
      width: 300,
      height: 175,
    },
    {
      id: 'accountssummary',
      parent: 'api',
      title: 'Accounts Summary Controller',
      description:
        'Provides customers with a summary of their bank accounts.',
      technology: 'Spring MVC Rest Controller',
      kind: 'component',
      level: 1,
      children: [],
      x: 780,
      y: 80,
      width: 300,
      height: 175,
    },
    {
      id: 'resetpw',
      parent: 'api',
      title: 'Reset Password Controller',
      description: "Allows users to reset their passwords with a single-use URL.",
      technology: 'Spring MVC Rest Controller',
      kind: 'component',
      level: 1,
      children: [],
      x: 1120,
      y: 80,
      width: 300,
      height: 175,
    },
    {
      id: 'security',
      parent: 'api',
      title: 'Security Component',
      description: 'Provides functionality related to signing in, changing passwords, etc.',
      technology: 'Spring Bean',
      kind: 'component',
      level: 1,
      children: [],
      x: 440,
      y: 295,
      width: 300,
      height: 175,
    },
    {
      id: 'mbsfacade',
      parent: 'api',
      title: 'Mainframe Banking System Facade',
      description: 'A facade over the mainframe banking system.',
      technology: 'Spring Bean',
      kind: 'component',
      level: 1,
      children: [],
      x: 780,
      y: 295,
      width: 300,
      height: 175,
    },
    {
      id: 'emailcomponent',
      parent: 'api',
      title: 'E-mail Component',
      description: 'Sends e-mails to users.',
      technology: 'Spring Bean',
      kind: 'component',
      level: 1,
      children: [],
      x: 1120,
      y: 295,
      width: 300,
      height: 175,
    },
    {
      id: 'mbs',
      parent: null,
      title: 'Mainframe Banking System',
      kind: 'externalSystem',
      level: 0,
      children: [],
      x: 1520,
      y: 80,
      width: 320,
      height: 182,
    },
    {
      id: 'email',
      parent: null,
      title: 'E-mail System',
      kind: 'externalSystem',
      level: 0,
      children: [],
      x: 1520,
      y: 295,
      width: 320,
      height: 182,
    },
  ],
  edges: [
    { id: 'spa-signin', parent: null, source: 'spa', target: 'signin', label: 'Makes API calls to', points: [] },
    { id: 'spa-accountssummary', parent: null, source: 'spa', target: 'accountssummary', label: 'Makes API calls to', points: [] },
    { id: 'spa-resetpw', parent: null, source: 'spa', target: 'resetpw', label: 'Makes API calls to', points: [] },
    { id: 'mobileapp-signin', parent: null, source: 'mobileapp', target: 'signin', label: 'Makes API calls to', points: [] },
    { id: 'mobileapp-accountssummary', parent: null, source: 'mobileapp', target: 'accountssummary', label: 'Makes API calls to', points: [] },
    { id: 'mobileapp-resetpw', parent: null, source: 'mobileapp', target: 'resetpw', label: 'Makes API calls to', points: [] },
    { id: 'signin-security', parent: null, source: 'signin', target: 'security', label: 'Uses', points: [] },
    { id: 'accountssummary-mbsfacade', parent: null, source: 'accountssummary', target: 'mbsfacade', label: 'Uses', points: [] },
    { id: 'resetpw-mbsfacade', parent: null, source: 'resetpw', target: 'mbsfacade', label: 'Uses', points: [] },
    { id: 'resetpw-emailcomponent', parent: null, source: 'resetpw', target: 'emailcomponent', label: 'Uses', points: [] },
    { id: 'mbsfacade-mbs', parent: null, source: 'mbsfacade', target: 'mbs', label: 'Makes API calls to [XML/HTTPS]', points: [] },
    { id: 'emailcomponent-email', parent: null, source: 'emailcomponent', target: 'email', label: 'Sends e-mail using [SMTP]', points: [] },
  ],
}

export interface BaseC4TemplateOption {
  level: 1 | 2 | 3
  label: string
  view: LikeC4View
}

export const BASE_C4_TEMPLATES: BaseC4TemplateOption[] = [
  { level: 1, label: 'Level 1 — System Context', view: LEVEL1_TEMPLATE },
  { level: 2, label: 'Level 2 — Container', view: LEVEL2_TEMPLATE },
  { level: 3, label: 'Level 3 — Component', view: LEVEL3_TEMPLATE },
]
